name: issue
on:
  issues:
    types:
      - opened

jobs:
  issue:
    name: ok
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: gh issue comment $ISSUE_URL -b "thank you $ISSUE_AUTHOR, your issue ($ISSUE_TITLE) have been taken into account"
